document.addEventListener("DOMContentLoaded", function() {
    // List of quotes
    const quotes = [
    "Believe you can and you're halfway there",
    "The only way to do great work is to love what you do",
    "Success is not final, failure is not fatal: It is the courage to continue that counts",
    "Hardships often prepare ordinary people for an extraordinary destiny",
    "I can't change the direction of the wind, but I can adjust my sails to always reach my destination",
    "No act of kindness, no matter how small, is ever wasted",
    "What you get by achieving your goals is not as important as what you become by achieving your goals",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle",
    "The future belongs to those who believe in the beauty of their dreams",
    "The only limit to our realization of tomorrow will be our doubts of today",
    "Creativity is intelligence having fun",
    "Your limitation—it's only your imagination",
    "Push yourself, because no one else is going to do it for you",
    "Great things never come from comfort zones",
    "Dream it. Wish it. Do it",
    "Success doesn’t just find you. You have to go out and get it",
    "The harder you work for something, the greater you’ll feel when you achieve it",
    "Dream bigger. Do bigger",
    "Don’t stop when you’re tired. Stop when you’re done",
    "Wake up with determination. Go to bed with satisfaction",
    "Do something today that your future self will thank you for",
    "Little things make big days",
    "It’s going to be hard, but hard does not mean impossible",
    "Don’t wait for opportunity. Create it",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths",
    "The key to success is to focus on goals, not obstacles",
    "Dream it. Believe it. Build it",
    "Sometimes later becomes never. Do it now",
    "Great things never come from comfort zones",
    "Dream bigger. Do bigger",
    "Don’t stop when you’re tired. Stop when you’re done",
    "Wake up with determination. Go to bed with satisfaction",
    "Do something today that your future self will thank you for",
    "Little things make big days",
    "It’s going to be hard, but hard does not mean impossible",
    "Don’t wait for opportunity. Create it",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths",
    "The key to success is to focus on goals, not obstacles",
    "Dream it. Believe it. Build it",
    "Sometimes later becomes never. Do it now",
    "Great things never come from comfort zones",
    "Dream bigger. Do bigger",
    "Don’t stop when you’re tired. Stop when you’re done",
    "Wake up with determination. Go to bed with satisfaction",
    "Do something today that your future self will thank you for",
    "Little things make big days",
    "It’s going to be hard, but hard does not mean impossible",
    "Don’t wait for opportunity. Create it",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths",
    "The key to success is to focus on goals, not obstacles",
    "Dream it. Believe it. Build it",
    "Sometimes later becomes never. Do it now",
    "Great things never come from comfort zones",
    "Dream bigger. Do bigger",
    "Don’t stop when you’re tired. Stop when you’re done",
    "Wake up with determination. Go to bed with satisfaction",
    "Do something today that your future self will thank you for",
    "Little things make big days",
    "It’s going to be hard, but hard does not mean impossible",
    "Don’t wait for opportunity. Create it",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths",
    "The key to success is to focus on goals, not obstacles",
    "Dream it. Believe it. Build it",
    "Sometimes later becomes never. Do it now",
    "Great things never come from comfort zones",
    "Dream bigger. Do bigger",
    "Don’t stop when you’re tired. Stop when you’re done",
    "Wake up with determination. Go to bed with satisfaction",
    "Do something today that your future self will thank you for",
    "Little things make big days",
    "It’s going to be hard, but hard does not mean impossible",
    "Don’t wait for opportunity. Create it",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths",
    "The key to success is to focus on goals, not obstacles",
    "Dream it. Believe it. Build it",
    "Sometimes later becomes never. Do it now",
    "Great things never come from comfort zones",
    "Dream bigger. Do bigger",
    "Don’t stop when you’re tired. Stop when you’re done",
    "Wake up with determination. Go to bed with satisfaction",
    "Do something today that your future self will thank you for",
    "Little things make big days",
    "It’s going to be hard, but hard does not mean impossible",
    "Don’t wait for opportunity. Create it",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths",
    "The key to success is to focus on goals, not obstacles",
    "Dream it. Believe it. Build it",
    "Sometimes later becomes never. Do it now",
    "Great things never come from comfort zones",
    "Dream bigger. Do bigger",
    "Don’t stop when you’re tired. Stop when you’re done",
    "Wake up with determination. Go to bed with satisfaction",
    "Do something today that your future self will thank you for",
    "Little things make big days",
    "It’s going to be hard, but hard does not mean impossible",
    "Don’t wait for opportunity. Create it",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths",
    "The key to success is to focus on goals, not obstacles",
    "Dream it. Believe it. Build it",
    "Sometimes later becomes never. Do it now"
        // Add your list of 100 inspirational quotes here
    ];

    // Select the quote box element
    const quoteBox = document.querySelector(".quote-box");

    // Choose a random quote
    const randomIndex = Math.floor(Math.random() * quotes.length);
    const randomQuote = quotes[randomIndex];

    // Display the random quote in the quote box along with the title
    quoteBox.innerHTML = `<h4>Inspirational Quotes</h4><p>${randomQuote}</p>`;
    quoteBox.classList.add("loaded"); // Add loaded class to apply fade-in effect
});